// src/components/projectsData.ts
export const projects = [
  {
    num: "01",
    category: "frontend",
    title: "Spend.In",
    description: "Plateforme de gestion des dépenses professionnelles. Interface intuitive pour centraliser et analyser vos dépenses métier en un seul endroit.",
    stack: ["React.js", "TypeScript", "Tailwind CSS"],
    image: "/projetim1.png",
    live: "https://spendin-ftcw2.netlify.app/",
    github: "https://github.com/Owedjangdev/FTC-W2-epiphaneHouehanou",
  },
  {
    num: "02",
    category: "frontend",
    title: "Monito",
    description: "Plateforme de recherche et d'adoption d'animaux de compagnie. Connectez-vous avec les animaux qui correspondent à vos besoins.",
    stack: ["React.js", "TypeScript", "Tailwind CSS"],
    image: "/projetim2.png",
    live: "https://ftcmonito.vercel.app/",
    github: "https://github.com/Owedjangdev/FTC-W3-epiphaneHouehanou",
  },
  {
    num: "03",
    category: "frontend",
    title: "Vaultflow",
    description: "Plateforme d'analyse et de reporting pour données. Offre des insights profonds et des visualisations modernes pour une meilleure prise de décision.",
    stack: ["React.js", "TypeScript", "Tailwind CSS"],
    image: "/projetim4.png",
    live: "https://vavtflow-ftcw1.netlify.app/",
    github: "https://github.com/Owedjangdev/FTC-W1-epiphaneHouehanou",
  },
  {
    num: "04",
    category: "frontend",
    title: "Foodweb",
    description: "Site restaurant avec menu interactif et système de commande en ligne. Expérience culinaire moderne avec ambiance chaleureuse et conviviale.",
    stack: ["React.js", "TypeScript", "Tailwind CSS"],
    image: "/projetim3.png",
    live: "https://sitefoodresto.netlify.app/",
    github: "https://github.com/Owedjangdev/sitefoodresto",
  },
];